# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax

name: Infrastructure Deployment

on:
  push:
    branches: ['main']
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "8.0.x"
  NODE_VERSION: "20"
  TFPLAN_NAME: plan.tfplan
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
  TERRAFORM_VERSION: "1.14"

permissions:
  # pull-requests: write
  contents: read
  actions: read

jobs:
  tf-build:
    runs-on: ubuntu-latest

    steps:
    - name: git-checkout
      uses: actions/checkout@v6

    - name: terraform-setup
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: $TERRAFORM_VERSION
        # terraform_version: ${{ matrix.tfversion }}
  
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init -input=false

    - name: Cache Terraform plugins
      id: terraform-cache
      uses: actions/cache@v5
      with:
        path: .terraform
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-
  
    - name: Cache Info
      if: steps.terraform-cache.outputs.cache-hit != 'true'
      run: echo "caching TF plugins"
  
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false -out $TFPLAN_NAME

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v7
      with:
        name: terraform-plan
        # name: terraform-plan-${{ matrix.tfversion }}
        path: |
          *.tfplan


  tf-release:
    runs-on: ubuntu-latest
    needs:
    - tf-build
    steps:
    - name: List and manage artifacts
      uses: actions/github-script@v9
      with:
        script: |
          // List artifacts for this repository
          const artifacts = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          console.log(`Found ${artifacts.data.total_count} artifacts`);
          for (const artifact of artifacts.data.artifacts) {
            console.log(`Artifact: ${artifact.name}`);
          }

    - name: git-checkout
      uses: actions/checkout@v6

    - name: terraform-setup
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: $TERRAFORM_VERSION
  
    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan
    - name: Terraform Init
      id: init
      run: terraform init -input=false

    - name: Terraform Apply
      run: |
        ls -la
        terraform -version
        terraform apply -no-color -input=false -auto-approve $TFPLAN_NAME
